apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tps
spec:
  selector:
    matchLabels:
      app: nodes
  replicas: 0
  template:
    metadata:
      labels:
        app: nodes
    spec:
      containers:
      - name: tps
        image: deadlock/eos-tps:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: ChainId
          value: '0365870660fa09c7fe15870aeab6a30cf89aef6f96a9765ab63f2588b388eacf'
        - name: PRIVATE_KEY
          value: '5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3'
        - name: CONTRACT_NAME
          value: 'eosio.token'
        - name: ENDPOINT
          value: 'http://eosio-0.nodes.default.svc.cluster.local:8888'
        - name: FROM
          value: 'eosio'
        - name: TO
          value: 'bpa'
        - name: QUANTITY
          value: '0.0001 BOS'
        - name: INTERVAL
          value: '100'
