apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eosio
spec:
  selector:
    matchLabels:
      app: nodes
  serviceName: nodes
  replicas: 1
  template:
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: eosio
        image: deadlock/eos-dpos-pbft:v0.5.2
        volumeMounts:
        - name: data-dir
          mountPath: /root/.local/share/eosio/nodeos/data
  volumeClaimTemplates:
  - metadata:
      name: data-dir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: slow
      resources:
        requests:
          storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bp
spec:
  selector:
    matchLabels:
      app: nodes
  serviceName: nodes
  replicas: 26
  template:
    metadata:
      labels:
        app: nodes
    spec:
      terminationGracePeriodSeconds: 600
      containers:
      - name: bp
        image: deadlock/eos-dpos-pbft:v0.5.2
        volumeMounts:
          - name: n-nodes-config-config-ini
            mountPath: /root/.local/share/eosio/nodeos/config/config.ini
            subPath: config.ini
          - name: data-dir
            mountPath: /root/.local/share/eosio/nodeos/data
      volumes:
        - name: n-nodes-config-config-ini
          configMap:
            name: n-nodes-config
  volumeClaimTemplates:
  - metadata:
      name: data-dir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: slow
      resources:
        requests:
          storage: 1Gi

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: node
spec:
  selector:
    matchLabels:
      app: nodes
  serviceName: nodes
  replicas: 9
  template:
    metadata:
      labels:
        app: nodes
    spec:
      terminationGracePeriodSeconds: 1
      containers:
      - name: node
        image: deadlock/eos-dpos-pbft:v0.5.2
        volumeMounts:
          - name: n-nodes-config-config-ini
            mountPath: /root/.local/share/eosio/nodeos/config/config.ini
            subPath: config.ini
          - name: data-dir
            mountPath: /root/.local/share/eosio/nodeos/data
      volumes:
        - name: n-nodes-config-config-ini
          configMap:
            name: n-nodes-config
  volumeClaimTemplates:
  - metadata:
      name: data-dir
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: slow
      resources:
        requests:
          storage: 1Gi
